### PR TITLE
Upgrade to Zookeeper 3.4.7

### PR DESCRIPTION
**Pull request by oleksiyk**
- upgrade to Zookeeper v3.4.7 because 3.4.6 is no longer available:
```
curl --head http://apache.mirrors.tds.net/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
HTTP/1.1 404 Not Found
Date: Thu, 07 Jan 2016 10:35:02 GMT
Server: Apache
Connection: close
Content-Type: text/html; charset=iso-8859-1
```

- remove zookeeper-2049 patch because it is included in 3.4.7 release
- make curl or wget continue aborted downloads (or skip already downloaded file)

### CODE REVIEW

**Comment by mdlavin** [comment]
Looks good to me, I'll merge it.  Do you want me to publish a new version for you?

**Comment by mdlavin** [comment]
Sorry I misread your name, I thought you might have been a collaborator on the project already.  I'll publish a new version for you.

**Comment by oleksiyk** [comment]
Thanks!

**Comment by mdlavin** [comment]
Version 3.4.7-1 is now published, thanks for your contribution.

**Pull request merged**
