### PR TITLE
bump zookeeperVersion to 3.5.8

### PR DESCRIPTION
**Pull request by konstruktoid**
Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

## Description
Update `zookeeperVersion` to 3.5.8.

## Motivation and Context
https://zookeeper.apache.org/doc/r3.5.8/releasenotes.html
https://downloads.apache.org/zookeeper/zookeeper-3.5.8/apache-zookeeper-3.5.8.tar.gz.sha512

```
This is a bugfix release for 3.5 branch.
It fixes 30 issues, including third party CVE fixes, several leader-election related fixes and a compatibility issue with applications built against earlier 3.5 client libraries (by restoring a few non public APIs).
```

## How Has This Been Tested?
```
$ ZK_INSTALL_VERBOSE=1 npm install

> zookeeper@4.5.2 install REDACTED/Github/node-zookeeper
> node ./scripts/prepublish.js && npm run build

cd REDACTED/Github/node-zookeeper/deps
exec command -v shasum >/dev/null 2>&1 && shasum -a 512 apache-zookeeper-3.5.8.tar.gz || sha512sum apache-zookeeper-3.5.8.tar.gz
68d9894bf5cfd1eafeb6aa5b895aa2d125a501792f052fc0f6fe5f3bce81ec2e70a87a50a294101dc2e599d7ea4939ac0983179b8728e5fcc7cdde6bca02a006  apache-zookeeper-3.5.8.tar.gz
test -d REDACTED/Github/node-zookeeper/deps/zookeeper
mv apache-zookeeper-3.5.8/zookeeper-client/zookeeper-client-c REDACTED/Github/node-zookeeper/deps/zookeeper
cp -R REDACTED/Github/node-zookeeper/patches/autoreconf/* REDACTED/Github/node-zookeeper/deps/zookeeper
rm -rf REDACTED/Github/node-zookeeper/patches/autoreconf

> zookeeper@4.5.2 build REDACTED/Github/node-zookeeper:
[...]
```

## Checklist:
- [X] I have read the [code of conduct](https://github.com/yfinkelstein/node-zookeeper/blob/master/CODE-OF-CONDUCT.md).
- [X] I have read the [contributing guide](https://github.com/yfinkelstein/node-zookeeper/blob/master/CONTRIBUTING.md).
- [] I have updated the documentation accordingly (if applicable).

### CODE REVIEW

**Comment by DavidVujic** [comment]
Thank you @konstruktoid! I'll have a look at your PR within the next couple of days.

**Comment by DavidVujic** [comment]
I think this change will make the `npm install` process download the v.3.5.8 file from the Apache ZooKeeper servers. Since the bump to 3.5.x, this repo includes a local copy of the C-client source code to speed up the install process, especially for those behind a company firewall.

I will do some local testing and then merge this PR - and I will create a separate PR that will include an updated zipped source code library. When that one is merged, I can create a new package and publish it to npm.

Thank you @kuebk for reviewing!

**Comment by DavidVujic** [comment]
Hello again @konstruktoid - I have cloned your repo and branch. But the build is failing. I've confirmed it on both mac os x and on linux. Did you manage to build it (`npm install`)?

The error is: `Error: exec: configure: error: jute files are missing! Please run "ant compile_jute" while in the zookeeper top level directory.`

I think I know the cause of it, and it is because of the new source code packaging from Apache ZooKeeper. The source code does no longer include the "autoreconf" files as they did before. That is why this repo has a local prebuilt copy of it (and also a local zipped file with the source code as described earlier).

The solution is to update the autoreconf files stored and zipped in this repo, and update the zookeeper C source code zipped file.

Here's what I suggest: 
I will create a separate branch for this and will ping you when it's ready. Then you could redirect your Pull Request to that branch instead. When merged and tested, I can merge it to master.

Would that be okay for you @konstruktoid?

**Comment by konstruktoid** [comment]
@DavidVujic yeah it bult but with just a couple of test failing. will look out for the branch test.

**Comment by DavidVujic** [comment]
Thanks for replying @konstruktoid!

What tests failed?

Also, I am surprised that the build went well. Could you verify by cleaning up all ignored and untracked files & directories, and then installing? 

```bash
git clean -fdX
npm install
```

**Comment by konstruktoid** [comment]
After cleaning it fails catastrophically. :/
I'll do my best to find a solution, but writing npm modules isn't really something I'm experienced doing.
Found the `zookeeper` version diff during an supply chain audit.

```
> zookeeper@4.5.2 install <REDACTED>/Github/node-zookeeper
> node ./scripts/prepublish.js && npm run build

apache-zookeeper-3.5.8.tar.gz exists.
68d9894bf5cfd1eafeb6aa5b895aa2d125a501792f052fc0f6fe5f3bce81ec2e70a87a50a294101dc2e599d7ea4939ac0983179b8728e5fcc7cdde6bca02a006  apache-zookeeper-3.5.8.tar.gz

> zookeeper@4.5.2 build <REDACTED>/Github/node-zookeeper
> node-gyp configure build

  ACTION binding_gyp_libzk_target_build_zk_client_lib .
configure: error: jute files are missing! Please run "ant compile_jute" while in the zookeeper top level directory.
<REDACTED>/Github/node-zookeeper/node_modules/shelljs/src/common.js:401
      if (config.fatal) throw e;
                        ^

Error: exec: configure: error: jute files are missing! Please run "ant compile_jute" while in the zookeeper top level directory.

    at Object.error (<REDACTED>/Github/node-zookeeper/node_modules/shelljs/src/common.js:110:27)
    at execSync (<REDACTED>/Github/node-zookeeper/node_modules/shelljs/src/exec.js:102:12)
    at Object._exec (<REDACTED>/Github/node-zookeeper/node_modules/shelljs/src/exec.js:205:12)
    at Object.exec (<REDACTED>/Github/node-zookeeper/node_modules/shelljs/src/common.js:335:23)
    at exec (<REDACTED>/Github/node-zookeeper/scripts/helper.js:4:23)
    at Object.<anonymous> (<REDACTED>/Github/node-zookeeper/scripts/build.js:49:5)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
make: *** [.] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd <REDACTED>/Github/node-zookeeper
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zookeeper@4.5.2 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zookeeper@4.5.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <REDACTED>/.npm/_logs/2020-05-22T11_13_17_452Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zookeeper@4.5.2 install: `node ./scripts/prepublish.js && npm run build`
npm ERR! Exit status 1
```

Failing but testing with `ant`

```
$ git diff
diff --git a/deps/apache-zookeeper-3.5.6.tar.gz b/deps/apache-zookeeper-3.5.6.tar.gz
deleted file mode 100644
index ab89140..0000000
Binary files a/deps/apache-zookeeper-3.5.6.tar.gz and /dev/null differ
diff --git a/scripts/build.js b/scripts/build.js
index 829f0ae..a2029ab 100644
--- a/scripts/build.js
+++ b/scripts/build.js
@@ -47,6 +47,7 @@ if (env.isWindows) {
     }

     exec(configureCmd);
+    shell.exec(`ant compile_jute`);
     exec(makeCmd);
 }

diff --git a/scripts/prepublish.js b/scripts/prepublish.js
index c8a27b3..4d8024d 100644
--- a/scripts/prepublish.js
+++ b/scripts/prepublish.js
@@ -66,7 +66,7 @@ function clearPath() {
 }

 function moveFolder() {
-    const sourceCodeFolder = `${env.downloadedFolderName}/zookeeper-client/zookeeper-client-c`;
+    const sourceCodeFolder = `${env.downloadedFolderName}`;
     if (env.isWindows) {
         shell.cp('-r', sourceCodeFolder, env.sourceFolder);
         shell.rm('-rf', env.downloadedFolderName);
@@ -78,7 +78,7 @@ function moveFolder() {

 function applyPatches() {
     if (env.isWindows) {
-        const destination = `${env.sourceFolder}/src`;
+        const destination = `${env.sourceFolder}/zookeeper-client/zookeeper-client-c/src`;

         shell.sed('-i', '#include "zookeeper_log.h"', '#include "zookeeper_log.h"\n#include "winport.h"\n', `${destination}/zk_log.c`);
         shell.sed('-i', '#include "zookeeper.h"', '#include "winport.h"\n#include "zookeeper.h"\n', `${destination}/zk_adaptor.h`);
```

**Comment by DavidVujic** [comment]
I'm going to close this PR and add a separate issue at this repo. You are more than welcome to continue working on the issue. That would be very much appreciated!

**Pull request closed without merging**
