### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by DavidVujic**
Finally, I think the node-zookeeper project has support for Windows.

I know, this Pull Request is massive, and here's an attempt to clarify! Please let me know if you want several PRs instead of one.

#### Build scripts ####
All build scripts has been rewritten from `bash` to `JavaScript`, to be run in a `node` environment. This will make building on Windows possible.

#### Windows custom build steps ####
The ZooKeeper Client has to be built with `CMake` on Windows. The `binding.gyp` file also includes Windows specific libraries for Sockets. Sadly, there seems to be no support for patching as a terminal command on Windows, ~~that is why entire files are copied to the ZooKeeper directory~~ that is why individual lines are inserted by the `prepublish` script. 

#### Patches for bugs in the ZooKeeper C Client code ####
The C code uses preprocessors wrongly in a couple of files, that causes the important `winports.h` file not to be loaded. The patches in this project will fix that. 

#### Dropped support for old Node.js versions ####
I think supporting the two latest LTS versions of Node.js is very generous for a library. With version 8, there is almost 100% support for ES 201x which has simplified writing the build scripts a lot! Also, for future PRs, the code in the `lib` folder can be refactored and written in a more modern way.

#### Less warnings on Mac OS X ####
An update in the `binding.gyp` solves the issue with build targets older than the current Mac OS X version.

#### package.json formatting ####
The file is reformatted to nodejs/JSON standards. Before doing this change, the `package.json` file always was marked as  `changed` after running `npm install`, the command altered the file each time. That is no longer an issue. Also, I've added myself to the list of contributors. 

#### SemVer support ####
Since this PR contains breaking changes (dropped support for old node.js versions), I have bumped up the Major version of this package. A result of that is also leaving the version sync with the current ZooKeeper library. By using SemVer, there will be less issues for consumers of this library. Especially when wildcards are used, like `3.4.x`. SemVer will solve that.

### CODE REVIEW

**Comment by DavidVujic** [comment]
This will solve the issue #145. 

The issues #137 and #144 will also be solved.

**Comment by DavidVujic** [comment]
Ping @mdlavin 

I am very excited about this Pull Request, a lot of work and learning about C/C++, CMake and lots of other things.

This will solve issues for developers running on Windows, that has not been able to participate in projects using this library.

**Comment by mdlavin** [comment]
I think supporting Windows would be great! I feel completely incapable of reviewing this PR for a couple reasons:

1. I haven't used node-zookeeper in almost 2 years now
2. I don't have a windows setup to test with
3. It's a massive amount of changes

Does anybody want to step up and be a maintainer of this project? Somebody out there must be more actively using this project than I am.

**Comment by DavidVujic** [comment]
@mdlavin I would like to be a maintainer of this project. Are you the only current maintainer?

I have a personal wish list for future updates in this project 😄  
Example: 
- convert JavaScript code to ES 201x
- use N-API instead of Nan
- add unit tests and (if possible) integration tests to the build process.
- experiment with building a native JavaScript version with (emscripten/asm.js/wasm)

**Comment by DavidVujic** [comment]
@mdlavin This could make reviewing this PR a little bit easier:  Travis CI will now guarantee that building works on Linux, Mac OS X and Windows (see attached screenshot).

Currently I can only guarantee that running the code (example.js and a proprietary code base used in the organization I work at) in Windows by providing screenshots if you request it. I have verified it working in different VMs: one running on an iMac in VirtualBox, and the other one on a MacBook Pro in VmWare Fusion.

skarmavbild 2019-02-28 kl 09 59 11

**Comment by DavidVujic** [comment]
If You think it will help, I will gladly demo this PR via chat/screen share! I guess it is a challenge finding a suitable time for everyone, because of different time zones. Let me know if You want this! @mdlavin @yfinkelstein @kuebk

**Comment by DavidVujic** [comment]
The latest commit made this Pull Request less overwhelming. The "windows patch" feature now does a search-and-replace code in files, instead of an entire file copy of a source controlled C file.

**Comment by mdlavin** [comment]
@yfinkelstein I don't have time to maintain this project the way that it deserves and @DavidVujic has shown real interest and capability in managing it. Can you give him access to merge and publish npm packages?

**Comment by yfinkelstein** [comment]
Sure will do! Thank you both for supporting the project!
    	
    	

    	Get Outlook for iOS
    
  




On Sat, Mar 2, 2019 at 8:07 AM -0800, "Matt Lavin" <notifications@github.com> wrote:












@yfinkelstein I don't have time to maintain this project the way that it deserves and @DavidVujic has shown real interest and capability in managing it. Can you give him access to merge and publish npm packages?

**Comment by DavidVujic** [comment]
@yfinkelstein @mdlavin Great! I would like to merge this PR to the master branch. What do you think: 👍 or 👎?

**Comment by yfinkelstein** [comment]
@DavidVujic You are now a collaborator with merge access.
Feel free to merge provided you will stand by it in case there are any follow up issues raised.

**Comment by DavidVujic** [comment]
Great! This is me on npm: https://www.npmjs.com/~davidvujic

I'm not sure how collaboration works on npm, but I would guess it is similar as giving access here on GitHub? @yfinkelstein 

I would like to create new version of the package.

**Comment by yfinkelstein** [comment]
added to npmjs admin list

**Pull request merged**
